version: '3'

services:
  db:
    image: microsoft/mssql-server-linux
    restart: always
    ports:
      - "1401:1433"
    environment:
      - SA_PASSWORD=Sql!Expre55
      - ACCEPT_EULA=Y

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8888:80"
    restart: always
    environment:
      - DBHOST=172.18.0.1
      - DBNAME=openvoting
      - DBPORT=1401
      - DBUSERNAME=sa
      - DBPASSWORD=Sql!Expre55
      - ASPNETCORE_ENVIRONMENT=Development
